//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.COTIZACION = new HashSet<COTIZACION>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Id_Region { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual ICollection<COTIZACION> COTIZACION { get; set; }
    }
}
