//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETE_TURISTICO
    {
        public PAQUETE_TURISTICO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.COTIZACION = new HashSet<COTIZACION>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<COTIZACION> COTIZACION { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
